---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

* unzip activity.zip

```{r, echo=TRUE}
raw_activity = read.csv('activity.csv')
steps_activity <- na.omit(raw_activity)
head(steps_activity)
```

## What is mean total number of steps taken per day?

```{r, echo=TRUE}
steps_by_day <- aggregate(steps_activity$steps, list(date = steps_activity$date), sum)
hist(steps_by_day$x)
mean(steps_by_day$x)
median(steps_by_day$x)
```

## What is the average daily activity pattern?

```{r, echo=TRUE}
steps_by_interval <- aggregate(steps_activity$steps, list(interval = steps_activity$interval), mean)
names(steps_by_interval)[names(steps_by_interval)=="x"] <- "steps"
steps_by_interval$time = as.POSIXct(sprintf("%04d", steps_by_interval$interval), format="%H%M")
plot(steps_by_interval$time, steps_by_interval$steps, xlab='time', ylab='average number of steps')
```

Which interval has the maximum steps?

```{r, echo=TRUE}
head(subset(steps_by_interval[order(-steps_by_interval$steps),], select=c('interval', 'steps')), 1)
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
